# Generated by Django 2.1.5 on 2019-03-10 06:40

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20)),
                ('gpic', models.ImageField(upload_to='goods')),
                ('goriginal_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gdiscount_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gclick', models.IntegerField()),
                ('gsynopsis', models.CharField(max_length=200)),
                ('ginventory', models.IntegerField()),
                ('gpostage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gcontext', tinymce.models.HTMLField()),
                ('isDelete', models.BooleanField(default=False)),
                ('gadvertis', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.TypeInfo'),
        ),
    ]
