# Generated by Django 2.1.5 on 2019-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190310_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpostage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
