# Generated by Django 2.1.5 on 2019-03-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190310_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gsynopsis',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
