# Generated by Django 2.1.5 on 2019-03-27 12:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190310_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gadvertis',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gclick',
            field=models.IntegerField(default=0, verbose_name='人气'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gcontext',
            field=tinymce.models.HTMLField(default='', verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gdiscount_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='优惠价'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='ginventory',
            field=models.IntegerField(default=999, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goriginal_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(upload_to='goods', verbose_name='主图'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpostage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='邮费'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gsynopsis',
            field=models.CharField(default='', max_length=200, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gtitle',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='typeinfo',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='typeinfo',
            name='ttitle',
            field=models.CharField(max_length=20, verbose_name='分类标题'),
        ),
    ]
