# Generated by Django 2.1.5 on 2019-03-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190316_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressinfo',
            name='auser',
        ),
    ]
