# Generated by Django 2.1.5 on 2019-03-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190316_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uaddress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uemail',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ufullname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='upwd',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='utel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uzipcode',
            field=models.CharField(max_length=6),
        ),
    ]
