# Generated by Django 2.1.5 on 2019-03-16 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190316_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufullname', models.CharField(max_length=20)),
                ('uaddress', models.CharField(max_length=100)),
                ('uzipcode', models.CharField(max_length=6)),
                ('utel', models.CharField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uaddress',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ufullname',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='utel',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uzipcode',
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='auser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
    ]
