# Generated by Django 2.1.5 on 2019-03-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190316_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinfo',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
