# Generated by Django 2.1.5 on 2019-03-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_addressinfo_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='uzipcode',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
