# Generated by Django 2.1.5 on 2019-03-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190327_2016'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailinfo',
            name='ogoods',
        ),
        migrations.RemoveField(
            model_name='orderdetailinfo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='ocart',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='ogoods',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo'),
        ),
        migrations.DeleteModel(
            name='OrderDetailInfo',
        ),
    ]
