# Generated by Django 2.1.5 on 2019-03-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190327_2016'),
        ('order', '0002_auto_20190328_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocount', models.IntegerField(default=0)),
                ('ogoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='count',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='ogoods',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo'),
        ),
    ]
